### ISSUE TITLE
One modification about making the example work in MacOS

### ISSUE THREAD

**Issue by 2533245542** [uwrit/postgis-docker#3]
I was not able to run the example query code on MacOS and it turned out that the `localhost` part cannot be interpreted on MacOS. I instead made the below modification.

```
$ curl http://127.0.0.1:5000/latlong?q=1410+NE+Campus+Parkway%2c+Seattle%2c+WA+98195
```
where `127.0.0.1` should be the address of your Mac computer and can be obtained by inputting `ifconfig |grep inet` in terminal.

**Comment by 2533245542** [comment]
Later I found `curl http://localhost:5000/latlong?q=1410+NE+Campus+Parkway%2c+Seattle%2c+WA+98195` also worked on MacOS. This is very weird because I did not change anything.

**Comment by ndobb** [comment]
@2533245542 sorry for my very late reply to this issue. It sounds like you've resolved it for now so I'm closing the ticket.
